# Assignment – NumPy 2 (Advanced Concepts) & Pandas 1 (Pandas Foundations)

Complete answers and runnable Google Colab code for all 10 questions.


## Question 1 – NumPy Broadcasting

### Answer
**Broadcasting** is NumPy's mechanism for performing operations between arrays with compatible shapes without explicitly copying the smaller array.

NumPy compares array shapes **from right to left**. Two dimensions are compatible when:
1. They are equal, or
2. One of them is `1`.

Missing dimensions are treated as `1`. If the dimensions cannot satisfy these rules, broadcasting is not possible.

For example, a 2D array with shape `(2, 3)` can be added to a 1D array with shape `(3,)`. The 1D array is conceptually applied to each row without explicitly creating copies.


In [ ]:
# Q1
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr_1d = np.array([10, 20, 30])

result = arr_2d + arr_1d

print("2D array:")
print(arr_2d)
print("\n1D array:")
print(arr_1d)
print("\nResult after broadcasting:")
print(result)


## Question 2 – `axis=0` and `axis=1`

### Answer
A `(3, 4)` array can be created with `np.arange(12).reshape(3, 4)`.

For a 2D array:
- `axis=0` means the operation works **down the rows**, producing one result for each column.
- `axis=1` means the operation works **across the columns**, producing one result for each row.

The results differ because the operation is performed along different directions.


In [ ]:
# Q2
import numpy as np

arr = np.arange(12).reshape(3, 4)

print("Array:")
print(arr)

print("\nSum along axis=0 (column sums):")
print(np.sum(arr, axis=0))

print("\nSum along axis=1 (row sums):")
print(np.sum(arr, axis=1))


## Question 3 – Random numbers and `np.random.seed()`

### Answer
`np.random.seed()` sets the starting state of NumPy's pseudorandom number generator. Using the same seed makes the generated sequence reproducible.

- `np.random.rand()` generates values from a uniform distribution over `[0, 1)`.
- `np.random.randn()` generates values from the standard normal distribution with mean `0` and standard deviation `1`.
- `np.random.randint()` generates random integers from a specified range, with the upper bound excluded.

Using a seed is useful in experiments and machine-learning work when results need to be reproduced.


In [ ]:
# Q3
import numpy as np

np.random.seed(42)

uniform_data = np.random.rand(5)
normal_data = np.random.randn(5)
integer_data = np.random.randint(1, 11, size=5)

print("np.random.rand():")
print(uniform_data)

print("\nnp.random.randn():")
print(normal_data)

print("\nnp.random.randint():")
print(integer_data)


## Question 4 – `reshape()`, `flatten()`, `hstack()` and `vstack()`

### Answer
For the supplied code, `arr` contains values from `0` to `11`. `reshape(3, 4)` changes the view/shape of the array. Then `flatten()` creates a **new 1D copy**.

Therefore, after `reshaped[0, 0] = 99`, `reshaped` contains `99` at its first position, but `flat` still contains the original `0`.

The output is:
```text
[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
```

`np.hstack()` stacks arrays horizontally, increasing the number of columns. `np.vstack()` stacks arrays vertically, increasing the number of rows.


In [ ]:
# Q4
import numpy as np

arr = np.arange(12)
reshaped = arr.reshape(3, 4)
flat = reshaped.flatten()

reshaped[0, 0] = 99

print("reshaped:")
print(reshaped)

print("\nflat:")
print(flat)

# hstack example
a = np.array([[1], [2]])
b = np.array([[3], [4]])

print("\nhstack:")
print(np.hstack((a, b)))

# vstack example
c = np.array([[1, 2]])
d = np.array([[3, 4]])

print("\nvstack:")
print(np.vstack((c, d)))


## Question 5 – Pandas DataFrame and Series

### Answer
A **Pandas DataFrame** is a two-dimensional tabular data structure with rows and columns. A **Pandas Series** is a one-dimensional labeled data structure.

The Seaborn `tips` dataset can be loaded using `sns.load_dataset("tips")`.

- `head()` displays the first five rows by default, giving a quick view of the data.
- `shape` returns `(number_of_rows, number_of_columns)`.
- `info()` displays information about columns, data types, non-null counts, and memory usage.


In [ ]:
# Q5
import pandas as pd
import seaborn as sns

tips = sns.load_dataset("tips")

print("First five rows:")
print(tips.head())

print("\nShape:")
print(tips.shape)

print("\nInfo:")
tips.info()


## Question 6 – `.loc[]` vs `.iloc[]`

### Answer
`.loc[]` is **label-based** indexing. When slicing labels, the end label is generally **inclusive**.

`.iloc[]` is **integer-position-based** indexing. Its slice end is **exclusive**, following normal Python slicing rules.

Using the Titanic dataset:
- `.loc[0:5, ['sex', 'age', 'fare']]` selects rows labeled `0` through `5` and includes label `5`.
- `.iloc[0:5, [2, 3]]` selects the first five rows and the 3rd and 4th columns because positions `2` and `3` are zero-based.


In [ ]:
# Q6
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

loc_result = df.loc[0:5, ['sex', 'age', 'fare']]
iloc_result = df.iloc[0:5, [2, 3]]

print("Using .loc[]:")
print(loc_result)

print("\nUsing .iloc[]:")
print(iloc_result)


## Question 7 – Boolean filtering in Pandas

### Answer
The expression
```python
(df['age'] > 18) & (df['survived'] == 1)
```
selects rows where **both** conditions are true: the passenger's age is greater than 18 and the passenger survived.

Parentheses are required because Pandas uses bitwise operators such as `&` for element-wise logical operations, and Python's operator precedence means each comparison should be grouped explicitly.

If rows matching **either** condition are required, replace `&` with `|`.


In [ ]:
# Q7
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

result = df[(df['age'] > 18) & (df['survived'] == 1)]

print("Shape of filtered result:", result.shape)
print(result.head())


## Question 8 – Missing values

### Answer
Two major strategies for handling missing values are:

1. **Dropping:** remove rows or columns containing missing values.
2. **Filling/imputation:** replace missing values with an appropriate value such as a median, mean, mode, or another estimate.

Dropping is useful when only a small number of observations are missing and removing them will not significantly reduce the dataset or introduce bias. Filling is useful when many values are missing and retaining the observations is important.

For the Titanic dataset, the requested operations are:
- Drop rows where `age` is missing.
- Fill missing `age` values with the median.
- Fill missing `embarked` values with the mode.


In [ ]:
# Q8
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

# (a) Drop rows where age is missing
dropped_age = df.dropna(subset=['age'])

# (b) Fill missing age with median and embarked with mode
filled_df = df.copy()

filled_df['age'] = filled_df['age'].fillna(filled_df['age'].median())
filled_df['embarked'] = filled_df['embarked'].fillna(
    filled_df['embarked'].mode()[0]
)

print("Original shape:", df.shape)
print("After dropping missing age:", dropped_age.shape)

print("\nMissing values after filling:")
print(filled_df[['age', 'embarked']].isna().sum())


## Question 9 – IQR method and Winsorization

### Answer
The **Interquartile Range (IQR)** method detects outliers using the middle 50% of the data.

- `Q1` is the 25th percentile.
- `Q3` is the 75th percentile.
- `IQR = Q3 - Q1`.

The bounds are:
- **Lower bound** = `Q1 - 1.5 × IQR`
- **Upper bound** = `Q3 + 1.5 × IQR`

Values below the lower bound or above the upper bound are treated as outliers.

Instead of deleting them, **capping/Winsorizing** replaces values below the lower bound with the lower bound and values above the upper bound with the upper bound.


In [ ]:
# Q9
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

Q1 = df['fare'].quantile(0.25)
Q3 = df['fare'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['fare'] < lower_bound) | (df['fare'] > upper_bound)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

print("\nNumber of outliers:", len(outliers))
print(outliers[['fare']].head())

# Winsorize/cap instead of removing
df_capped = df.copy()
df_capped['fare'] = df_capped['fare'].clip(
    lower=lower_bound,
    upper=upper_bound
)

print("\nCapped fare values:")
print(df_capped['fare'].head())


## Question 10 – Encoding and standardization for machine learning

### Answer
**Label encoding** converts categorical values into numeric labels. For the binary `sex` column, the two categories can be mapped to `0` and `1`.

**One-hot encoding** creates separate binary columns for categories. `pd.get_dummies()` can be used for the `embarked` column.

**Z-score standardization** transforms a numerical variable using:
`x_scaled = (x - mean) / std`

Encoding is needed because many machine-learning algorithms require numerical inputs. Scaling is useful because features with very different numerical ranges can otherwise affect distance-based, gradient-based, or regularized models disproportionately.


In [ ]:
# Q10
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic").copy()

# (a) Label-encode binary sex column
df['sex_encoded'] = df['sex'].map({'female': 0, 'male': 1})

# (b) One-hot encode embarked
df = pd.get_dummies(df, columns=['embarked'], prefix='embarked', dtype=int)

# (c) Z-score standardization of fare
fare_mean = df['fare'].mean()
fare_std = df['fare'].std()

df['fare_scaled'] = (df['fare'] - fare_mean) / fare_std

print(df[['sex', 'sex_encoded', 'fare', 'fare_scaled']].head())

print("\nEncoded embarked columns:")
print([col for col in df.columns if col.startswith('embarked_')])


# End of Assignment

Run the code cells in Google Colab to see the outputs.